FROM golang:1.20 as builder

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY src ./src
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o /usr/local/bin/app ./src
#COPY /go/bin/dlv /dlv

#CMD tail -f

FROM golang:1.20
COPY --from=builder /usr/local/bin/app /app
COPY --from=builder /go/bin/dlv /dlv

#CMD tail -f
CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "/app"]
