// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/jinzhu/gorm"
	"krisha/src/internal/service"
	"krisha/src/internal/service/apartments"
	"krisha/src/internal/service/api"
	"krisha/src/internal/service/tg"
	"krisha/src/tghttp"
)

// Injectors from di.go:

func InitServices(db *gorm.DB) *Services {
	apsCacheService := apartments.NewApsCacheService()
	apsLoggerService := apartments.NewApsLoggerService()
	tgService := tg.NewTgService()
	apsTgSenderService := apartments.NewApsTgSenderService(tgService)
	krishaClientService := api.NewKrishaClientService()
	parserService := service.NewParserService(krishaClientService, apsCacheService, apsTgSenderService, apsLoggerService, tgService, db)
	tgInteractor := tghttp.NewTgInteractor(tgService)
	services := NewServices(apsCacheService, apsLoggerService, apsTgSenderService, krishaClientService, parserService, tgService, tgInteractor)
	return services
}
