// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"krisha/src/http"
	"krisha/src/internal"
	"krisha/src/internal/repo"
	"krisha/src/internal/service/apartments"
	"krisha/src/internal/service/api"
	"krisha/src/internal/service/parser"
	"krisha/src/internal/service/tg"
	"krisha/src/tghttp"
)

// Injectors from di.go:

func InitServices(db2 *gorm.DB, tgServicer tg.TgServicer) *Services {
	apsLoggerService := apartments.NewApsLoggerService()
	apsTgSenderService := apartments.NewApsTgSenderService(tgServicer)
	krishaClientService := api.NewKrishaClientService(tgServicer)
	parserSettingsRepository := repo.NewParserSettingsRepository(db2)
	factory := parser.NewParserFactory(tgServicer, krishaClientService)
	service := parser.NewParserService(parserSettingsRepository, tgServicer, factory, krishaClientService)
	allowedChatRepository := repo.NewAllowedChatRepository(db2)
	permissionsService := internal.NewPermissionsService(allowedChatRepository)
	tgInteractor := tghttp.NewTgInteractor(tgServicer, service, permissionsService)
	controller := http.NewController(tgInteractor, db2, service)
	mainServices := NewServices(apsLoggerService, apsTgSenderService, krishaClientService, service, tgServicer, tgInteractor, factory, controller)
	return mainServices
}
